In [1]:
import numpy as np

#### Автоматическое создание массивов

In [4]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

По умолчанию ряд чисел начинается с 0, но можно явно задать начало последовательности:

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

В обратном порядке:

In [12]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

В обратном порядке с шагом 2:

In [13]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

Дробный шаг

In [14]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

**numpy.linspace** - то же самое, но нужно учитывать, что правая граница будет включена.

Вместо шага указываем нужное количество элементов (100)

In [15]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

**np.logspace** - обе границы включены, но это не сами числа, а степени числа 10:

In [16]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

**np.random.sample** - случайные числа с равномерным распределением в промежутке [0.0, 1.0]

Случайное число

In [17]:
np.random.sample()

0.07372710886358469

Одномерный массив из 3х элементов

In [19]:
np.random.sample(3)

array([0.27373051, 0.33378476, 0.61946085])

Двумерный массив 2x3:

In [22]:
np.random.sample((2, 3))

array([[0.79285724, 0.55713897, 0.04838574],
       [0.84786316, 0.04122953, 0.15513397]])

Массив 48x64x3:

(например это может быть случайное изображение с высотой 48, шириной 64 и значениями яркости трех цветов для каждого пикселя)

In [24]:
np.random.sample((48, 64, 3))

array([[[0.3980597 , 0.21450358, 0.1296748 ],
        [0.16971361, 0.99177466, 0.94590695],
        [0.86952375, 0.11526578, 0.33282927],
        ...,
        [0.67912671, 0.73074247, 0.27821999],
        [0.39756659, 0.0700057 , 0.7256174 ],
        [0.03961457, 0.38046669, 0.50490162]],

       [[0.05500948, 0.51967284, 0.12743226],
        [0.00385984, 0.978837  , 0.64168199],
        [0.44128197, 0.97975512, 0.57509969],
        ...,
        [0.04085265, 0.8637421 , 0.05558415],
        [0.25020045, 0.98887114, 0.0476103 ],
        [0.21968958, 0.43804529, 0.03525445]],

       [[0.03461431, 0.01580397, 0.14981623],
        [0.51297198, 0.93725717, 0.55286799],
        [0.61850315, 0.09159985, 0.1864944 ],
        ...,
        [0.01394977, 0.94230154, 0.55625104],
        [0.60927414, 0.95965464, 0.7450695 ],
        [0.67082269, 0.27317036, 0.32018263]],

       ...,

       [[0.00705516, 0.97235354, 0.96520265],
        [0.11621054, 0.98907865, 0.37867644],
        [0.8829307 , 0

**numpy.random.randn** - случайные числа с нормальным распределением

(среднее значение = 0, среднеквадратичное отклонение = 1)

In [26]:
np.random.randn(10)

array([-0.38057092,  1.1522698 , -0.51984206, -1.03518539,  0.50428422,
        1.64444582, -0.5335429 , -0.81098392,  0.905633  , -0.4944763 ])

In [27]:
np.random.randn(3, 4)

array([[ 0.08580636, -0.53981876, -1.78492079,  1.5445402 ],
       [ 0.4320837 , -0.62100625,  0.25268849,  1.08296596],
       [ 1.43155732,  0.32319002, -0.49796524,  0.86740847]])

**numpy.random.randint** - массив из целых чисел

Например, одномерный массив из 10 случайных чисел в промежутке [0, 100]

In [28]:
np.random.randint(0, 100, 10)

array([52, 68, 55, 32, 29,  3, 96,  8, 16, 15])

Двумерный массив 3x4 из случайных чисел в промежутке [0, 10]

In [29]:
np.random.randint(0, 10, (3, 4))

array([[7, 3, 4, 6],
       [0, 9, 4, 2],
       [5, 1, 8, 6]])

**numpy.random.choice** - случайный выбор элементов из массива

In [30]:
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [31]:
np.random.choice(b)

8

In [32]:
np.random.choice(b, 3)

array([3, 2, 6])

**numpy.random.seed** - инициализация генератора случайных чисел.

Может использоваться для последующей воспроизводимости (будут генерироваться те же числа, если установить одинаковый seed)

In [35]:
np.random.seed(42)

In [36]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

#### Изменение формы массива

In [40]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
# Можно указать требуемое число строк, а вместо числа столбцов поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
# inplace
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Соединение массивов

Для наглядности возьмем два массива с нулями и единицами

In [52]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [59]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [62]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [63]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину (в третьем измерении)

In [65]:
d = np.dstack((a, b))
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])