### Операции с веторами

Загрузим библиотеку NumPy:

In [3]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3, 4])

In [14]:
b = np.array([5, 6, 7, 8, 9])

In [6]:
a.size

5

In [7]:
b.size

5

In [8]:
a.shape

(5,)

In [9]:
b.shape

(5,)

#### Сложение векторов

In [13]:
c = a + b

In [15]:
c

array([ 5,  7,  9, 11, 13])

Сравним, что делает оператор "+" со списками в Python

In [17]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [18]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Еще один способ

In [19]:
c = np.add(a, b)

In [20]:
c

array([ 5,  7,  9, 11, 13])

#### Вычитание векторов

In [22]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [23]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

Альтернативный способ

In [27]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

При вычитании векторов их размерность должна совпадать

In [28]:
a.shape == b.shape

True

#### Умножение вектора на скаляр

In [29]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [31]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [34]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [37]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

Сравним с умножением натурального числа на список
(результат не тот - увеличение длины списка, а не умножение вектора на скаляр)

In [38]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

Альтернативные способы умножения массива на скаляр

In [39]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [41]:
# Вариант 1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [42]:
# Вариант 2
np.dot(a, -10)

array([-50, -40, -80, -40, -30])

In [44]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

#### Скалярное произведение векторов

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [46]:
a.shape

(3,)

In [47]:
b.shape

(3,)

In [49]:
sp = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
sp

32

In [53]:
# Вариант 1
sp = a @ b
sp

32

In [54]:
# Вариант 2
sp = np.dot(a, b)
sp

32

### Операции с матрицами

In [58]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [57]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [59]:
A.shape

(3, 2)

In [60]:
B.shape

(3, 2)

#### Сложение матриц

In [62]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Альтернативный способ

In [63]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Вычитание матриц

In [66]:
A = np.array([[11, 13],
              [16,  9],
              [ 8, 15]])

In [67]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [68]:
D = A - B
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

In [69]:
D = np.subtract(A, B)
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

#### Умножение матрицы на скаляр

In [70]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [72]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [74]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])